version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_backend
    env_file:
      - ./backend/env.postgres
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network


networks:
  app_network:
